#!/bin/sh

set -euo pipefail

# Initialization - load function handler
# source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"

./php_phalcon/bin/php -S 0.0.0.0:8000 -t public .htrouter.php & PHP_PID=$!
# Sleep hack to avoid a simple race condition on first request
sleep .1

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Execute the handler function from the script
  RESPONSE=$(curl -X POST "0.0.0.0:8000/" -d "$EVENT_DATA")
  
  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" -d "$RESPONSE"
done

kill $PHP_PID
